### ISSUE TITLE
Add build pipeline

### ISSUE THREAD

**Issue by gavanlamb** [gavanlamb/library-logging-serilog#10]
## Linked to 
- [x] #5 

## Tasks
- [ ] Build structure
    - [ ] Create a code release and version appropriately if it's the main branch
    - [x] Version generator using NBGV
    - [ ] Get release notes and assign them to a variable
        - [ ] https://github.com/marketplace/actions/release-changelog-builder
    - [x] Restore packages
    - [x] Run NuGet outdated
    - [x] dotnet format
    - [x] Build for:
        - [x] Linux
            - [x] dotnet 6
            - [x] dotnet 7
            - [x] dotnet 8
    - [x] Run unit tests 
    - [ ] Generate report and add comment
    - [x] Generate code coverage report
    - [x] Run Stryker
    - [x] Generate stryker report
    - [x] Package
    - [x] Create artifact
- [x] Release
- [x] Create a badge
- [ ] Update readme
- [ ] Build documentation 

Build summary output
- [ ] Version information
- [ ] Badges (coverage, mutation, version)
- [ ] Link to mutation report
- [ ] Link to coverage report

Apply comment to the PR too

Add a job results like `Test Results` for
- [ ] coverage
- [ ] Mutation
- [ ]
