### ISSUE TITLE
Upgrade implementation to support IHostBuilder & WebApplicationBuilder

### ISSUE THREAD

**Issue by gavanlamb** [gavanlamb/library-logging-serilog#6]
## Linked to 
- [x] #5 

## Tasks
- [x] Update PR template
- [x] Upgrade package
- [x] Support dotnet 6
- [x] Support dotnet 7
- [x] Support dotnet 8
- [x] Create extension methods for IHostBuilder 
- [x] Create extension methods for WebApplicationBuilder
- [x] Update readme.md
